config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  get 'static_pages/login'

  root 'static_pages#landing'

  resources :articles

  get ':action' => 'static_pages#:action'
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :body,  presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :github_address, presence: true

  has_attached_file :screenshot
  validates_attachment :screenshot, content_type: { content_type: ['image/jpg', 'image/jpeg'] }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:index]
  @@markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, extensions = {})

  def index
    @article = Article.new

    @articles = grab_sorted_articles
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.save
    @articles = grab_sorted_articles

    render 'index'
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end

  def require_login
    redirect_to '/login' unless user_signed_in?
  end

  def grab_sorted_articles
    articles = Article.all.sort do |x,y|
      y.created_at <=> x.created_at
    end

    articles.each { |art| art.body = @@markdown.render art.body }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:index]

  def index
    @project = Project.new
    @projects = Project.all
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    @project.save
    @projects = Project.all

    render 'index'
  end

  def update
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(
      :title,
      :description,
      :github_address,
      :screenshot
    )
  end

  def require_login
    redirect_to '/login' unless user_signed_in?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:login]

  def about
  end

  def login
  end

  def landing
  end

  def resume
    send_file(
      File.join(Rails.root, 'app', 'assets', 'GregoryDiamondResume.pdf'),
      filename: 'GregoryDiamondResume.pdf',
      type: 'application/pdf',
      disposition: 'inline'
    )
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Greg Diamond"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.label :title, id: 'input-title' %></br>
  <p>Your text should be in markdown format.</p>
  <%= f.text_field :title, id: 'input-title-text' %></br>

  <%= f.label :body, id: 'input-body' %></br>
  <%= f.text_area :body, id: 'input-body-text' %></br>

  <%= f.submit id: 'submit-button' %></br>

<% end %>

app/views/articles/index.html.erb
<% if user_signed_in? %>
  <%= render 'form' %>
<% end %>

<div class="row">
  <div class="col-md-1 col-lg-2"></div>
  <div class="col-md-10 col-lg-8">
    <% @articles.each do |article| %>
      <div class="articleholder">
        <h3 class="date"><%= article.created_at.strftime('%A, %B %d, %Y') %></h3>
        <h2 class="title"><%= article.title %></h2>
        <div class="body">
          <%= raw article.body %>
        </div>

        <% if user_signed_in? %>
          <%= link_to "EDIT", edit_article_path(article) %>
          <%= link_to "DELETE", article_path(article),
            method: :delete,
            data: { confirm: "Are you sure you want to delete this?" } %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-1 col-lg-2"></div>
  <div class="col-md-10 col-lg-8">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- blog ad -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-1708213136285086"
         data-ad-slot="1240152450"
         data-ad-format="auto"></ins>
    <script>
(adsbygoogle = window.adsbygoogle || []).push({});
    </script>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container-fluid footer-container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <%= link_to fa_icon('twitter').html_safe, 'https://twitter.com/greg_diamond29', class: 'btn social-icon' %>
        <%= link_to fa_icon('github').html_safe, 'https://github.com/diamond29', class: 'btn social-icon' %>
        <%= link_to fa_icon('linkedin-square').html_safe, 'https://www.linkedin.com/in/gregory-diamond-a6404596', class: 'btn social-icon' %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 text-center">
        <%= link_to "About This Site", 'about', class: 'btn' %>
        <%= mail_to 'gregdiamond29@gmail.com', 'Contact', class: 'btn' %>
      </div>
    </div>
    <div class="row copyright-row">
      <div class="col-sm-12 text-center">
        <span>© 2015 Gregory Diamond. All rights reserved.</span>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top greg-navbar">
  <div class="container-fluid">
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsible-menu" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'GD', root_path, { class: "navbar-brand", id: 'logo'} %>
      </div>
      <div class="collapse navbar-collapse" id="collapsible-menu">
        <ul class="nav navbar-nav navbar-right greg-navbar-links">
          <li><%= link_to "Home", root_path, class: "greg-link" %></li>
          <li><%= link_to "Blog", articles_path, class: "greg-link" %></li>
          <li><%= link_to "Projects", projects_path, class: "greg-link"%></li>
          <li><%= link_to "Github", 'https://github.com/diamond29', class: "greg-link" %></li>
          <li><%= link_to "Resume", 'resume', { class: "greg-link", target: '_blank' } %></li>
          <li><%= mail_to 'gregdiamond29@gmail.com', 'Contact', class: "greg-link" %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          <% end %>
        </ul>
      </div>
    </nav>
    <% if lookup_context.find_all("#{controller.controller_name}/_#{controller.action_name}_header").any? %>
      <div class="header-content <%= controller.controller_name %>-header" >
        <%= render :partial => "#{controller.action_name}_header" rescue nil %>
        <div class="text-center">
          <a href="#page-content" class="btn"><%= fa_icon('chevron-down') %></a>
        </div>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>
<div id="page-content" class="container main-body <%= controller.controller_name %>">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>

<% parent_layout 'base' %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html lang='en'>
  <link href='http://fonts.googleapis.com/css?family=Alfa+Slab+One' rel='stylesheet' type='text/css'>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body >
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, html: { multipart: true } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %></br>
  <%= f.text_field :title %></br>

  <%= f.label :github_address %></br>
  <%= f.text_field :github_address %></br>

  <%= f.label :description %></br>
  <%= f.text_area :description %></br>

  <%= f.label 'Project Screenshot' %></br>
  <%= f.file_field :screenshot %>

  <%= f.submit %>
<% end %>

app/views/projects/_index_header.html.erb
<h1 class="text-center header-title">Projects</h1>

app/views/projects/_node.html.erb
<div class="node">
  <div class="node-photo" <% if project.screenshot.file? %>style="background-image: url(<%= project.screenshot.url %>)" <% end %>>
    <div class="node-photo-cover">
      <div class="node-photo-content">
	<%= link_to "VIEW IT ON GITHUB", project.github_address, class: 'greg-link' %>
      </div>
    </div>
  </div>
  <div class="node-text">
    <h2><%= project.title %></h2>
    <hr/>
    <p><%= project.description %></p>

  <% if user_signed_in? %>
    <%= link_to "EDIT", edit_project_path(project) %>
    <%= link_to "DELETE", project_path(project),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this?" } %>
  <% end %>

  </div>
</div>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<h3 class="text-center">Still adding things - work in progress.</h3>

<% if user_signed_in? %>
  <%= render 'form' %>
<% end %>

<% slice_size = 2 %>

<% @projects.each_slice(slice_size) do |proj_slice| %>
  <div class="row">

    <% if proj_slice.size == slice_size %>
      <% proj_slice.each do |project| %>
        <div class="col-md-6">
          <%= render 'node', project: project %>
        </div>
      <% end %>
    <% else %>
      <div class="col-md-offset-3 col-md-6">
        <%= render 'node', project: proj_slice[0] %>
      </div>
    <% end %>
  </div>

<% end %>

app/views/static_pages/_about_header.html.erb
<div class="row headline-row">
  <div class="col-sm-12 headline-col text-center">
    <h1>About This Site</h1>
  </div>
</div>

app/views/static_pages/_landing_header.html.erb
<div class= "landing-content">
  <div class="row headline-row">
    <div class="col-sm-12 headline-col text-center">
      <h1>DEVELOPER.</h1>
    </div>
  </div>
  <div class="row link-row">
    <div class="col-xs-12">
      <div class="btn-toolbar text-center">
        <%= link_to "Resume",'resume', { class: 'btn landing-link', target: '_blank' } %>
        <%= mail_to 'gregdiamond29@gmail.com', "Contact", class: 'btn landing-link' %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_tweets.html.erb
<a class="twitter-timeline"  href="https://twitter.com/greg_diamond29" data-widget-id="673949284870561792" data-chrome="nofooter noscrollbar transparent" data-tweet-limit="3">Tweets by @greg_diamond29</a>
<script>
!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
</script>

app/views/static_pages/about.html.erb
<div class="row">
  <div class="col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8 about-content">
    <%= link_to "Click here for all of the code", "https://github.com/diamond29/gregdiamondio", class: "btn code-btn center-block" %>

    <p>
    This site is an open source ruby on rails application. Anyone can run a copy of this site themselves. It's not backed with an extensive cms, so most of it is coded with my name and relevant links, but there are some cms elements for the blogging functionality.
    </p>
    <br/>
    <p>
    I'm a big fan of open source software and Github. I love being able to look at the source for the code I'm running or using. That's why I chose to make my site totally open source. I also love ruby, which is why this site is written using ruby on rails.
    </p>
  </div>
</div>

app/views/static_pages/landing.html.erb
<div class="row">
  <div class="col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8 text-center">
    <div class="row-content">
      <h1>A bit about me</h1>
      <p>
      Since I was young, I've found myself drawn to computers. I started off with video games, but nowadays, I look for challenges in coding clean and extensible solutions to problems. I also enjoy compelling movies, new restaurants and good beers.
      </p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8 text-center">
    <div class="row-content">
      <h1>Blog Links/Summaries Here</h1>
      <p>Work in progress.</p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8 text-center">
    <div class="row-content">
      <h1>Project Links/Summaries Here</h1>
      <p>Work in progress.</p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8 text-center">
    <div class="row-content">
      <%= render 'tweets' %>
    </div>
  </div>
</div>

app/views/static_pages/login.html.erb
<div class="center jumbotron">
  <h1>Successfully logged in!</h1>
</div>

app/views/visitors/index.html.erb
<div class="container-fluid" ng-app="visitors">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h1 ng-if="name">Hello, {{name}}</h1>
    </div>
    <div class="panel-body">
      <form class="form-inline">
        <div class="form-group">
          <input class="form-control" type="text" placeholder="Enter your name" autofocus ng-model="name">
        </div>
      </form>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="center jumbotron">
  <h1>Under construction...</h1>

  <h2>
    Future home of Greg Diamond's personal website.
  </h2>
</div>